### ISSUE TITLE
PROTOCOLS=ISO_15118_20_AC doesn't work normally

### ISSUE THREAD

**Issue by GUANMINLIAO** [SwitchEV/iso15118#216]
Hello:
          When I type PROTOCOLS=ISO_15118_20_AC in .env file, it's doesn't work normally.Does this problem need me to adjust any settings?Or is it a bug? Thank you!

**Comment by tropxy** [comment]
Hi, can you include the message logs so we can inspect the issue?

**Comment by GUANMINLIAO** [comment]
Hi @tropxy 

Sorry,it is late for response.
First,I type "PROTOCOLS=ISO_15118_20_AC" in .env file.
![image](https://user-images.githubusercontent.com/92351561/231656279-2cbeab76-e61f-4538-8d86-3f5e413b40b3.png)

Then, this is SECC log:
![image](https://user-images.githubusercontent.com/92351561/231656432-a392732d-ab4b-4dcf-98f2-aa23be7accd9.png)

and EVCC log is below:
![image](https://user-images.githubusercontent.com/92351561/231656561-f9d4b397-a675-4a81-b687-c738f47c10cb.png)


Could you please tell me if there is any method to slove this issue, Many thanks!

**Comment by shalinnijel2** [comment]
The failure happened during supportedAppProtocol request - even though the secc is configured to offer -20, it seems the EV requested only -2. From the above .env file, EVCC_CONFIG_PATH is pointing at the sample -2 config. Could you try updating it as follows and retry?
```
EVCC_CONFIG_PATH=iso15118/shared/examples/evcc/iso15118_20/evcc_config_ac_bpt.json
```

**Comment by GUANMINLIAO** [comment]
Hi @shalinnijel2 

It runs normally on the shell. Many thanks for the help!
