### ISSUE TITLE
Regarding the problems encountered in running the ISO15118 project on the ARMv7 development board？

### ISSUE THREAD

**Issue by Baymax-Rob** [SwitchEV/iso15118#222]
1. Poetry cannot be installed through python's virtual environment management dependencies, such as: pipx, venv, etc., it will prompt an error: cffi, coverage cannot be installed, error: /arm-linux-gnueabihf- gcc failed: No such file or directory.
2. I tried to install to the local root file system through pip, and the installation was successful, but when poetry install, the same error will be reported: /arm-linux-gnueabihf- gcc failed: No such file or directory.
3. Does the ISO15118 project operate without using poetry to manage its operation?
The kernel version of the current development board is: linux-5.10.50

**Comment by shalinnijel2** [comment]
_Does the ISO15118 project operate without using poetry to manage its operation?_
Apologies for the lates response - yes, the iso15118 project will work without using poetry. 'pip install .' in the root should install the required dependencies. I will close the ticket for now. Please feel free to reopen if you have more questions.
