### ISSUE TITLE
No way to know when to change to CP State C in EVCC

### ISSUE THREAD

**Issue by heavyweight87** [SwitchEV/iso15118#264]
There is currently no way to know when to change the CP state to state C in the EVCC side. 
There is a TODO (in DIN SPEC) but no implementation

For now I solved this by adding a set_cp_state_c to the interface/simulator class

Is it possible to add this? I can add and make a pull request if it helps

**Comment by shalinnijel2** [comment]
Yes, please go ahead and open a PR. Thank you in advance for your contribution. :).

**Comment by shalinnijel2** [comment]
Fixed under #368
