### ISSUE TITLE
"make build" error occurs

### ISSUE THREAD

**Issue by coollhc77** [SwitchEV/iso15118#268]
"make build" error occurs.
Running "pip install --upgrade pip" gives the same error.
Please, can anyone help me?

[make_build.txt](https://github.com/SwitchEV/iso15118/files/11931754/make_build.txt)

**Comment by Baymax-Rob** [comment]
In your makefile log, error: can't find Rust compiler. , you must first install the rust compiler,
` curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |sh`

**Comment by coollhc77** [comment]
Baymax-Rob You're right, the Rust compiler is not installed.
I had problems with Raspbian 32bit, 64bit works fine.
Thanks.

**Comment by coollhc77** [comment]
.
