### ISSUE TITLE
Runing DC in 0.20.0

### ISSUE THREAD

**Issue by GUANMINLIAO** [SwitchEV/iso15118#270]
Could I ask a problem about this?

How do I set in the .env file to run the iso15118-20 dc ?
The following is my .env file running iso15118-20 ac:
![image](https://github.com/SwitchEV/iso15118/assets/92351561/6e686cf8-2cee-4e8e-913a-64054105c62d)
Many thanks!

**Comment by Baymax-Rob** [comment]
In the readme of this project：Enabled communication protocols on EVCC. NOTE: ISO 15118 DC support is still under development.

**Comment by shalinnijel2** [comment]
Two changes:
1. To support secc to offer 15118-20 DC, set:
```
PROTOCOLS=ISO_15118_20_DC
```
2. To set evcc to request dc, set evcc to use the following example config:
```
EVCC_CONFIG=iso15118/shared/examples/evcc/iso15118_20/evcc_config_dc_bpt.json
```
@Baymax-Rob Thank you for pointing that out. Will update the readme. DC support was added some time ago. This comment was missed.
