### ISSUE TITLE
make install-local 

### ISSUE THREAD

**Issue by KhaledEssam24** [SwitchEV/iso15118#360]
While I was running this command ,I got this error 
I'm using ubuntu 22 & python 3.10

poetry install
Traceback (most recent call last):
  File "/home/khaled/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/usr/lib/python3/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/lib/python3/dist-packages/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ImportError: cannot import name 'Application' from 'cleo' (/home/khaled/.local/lib/python3.10/site-packages/cleo/__init__.py)
make: *** [Makefile:78: install-local] Error 1

**Comment by shalinnijel2** [comment]
After taking a quick look, cleo doesn't seem to be a dependency that iso15118 uses. Just to be sure we are working on a clean setup, could you also try creating a new virtual env and then run [`make install-local`](https://github.com/SwitchEV/iso15118/blob/375cd0bb66505321ac4390578f051138575161ec/Makefile#L21) or poetry install like you did?

**Comment by KhaledEssam24** [comment]
this will solve the issue 

rm `which poetry`
curl -sSL https://install.python-poetry.org | python -
