### ISSUE TITLE
Possible issue reported by Designwerk with the TCP server (binding to interface)

### ISSUE THREAD

**Issue by tropxy** [SwitchEV/iso15118#37]
According to Lukas, from Designwerk, they experienced issues when starting the SECC side, specifically they reported the bind to the IPv6 IP address would not work and they did the following change in the tcp_server.py:

```python
    async def server_factory(self, tls: bool) -> None:
        port = self.port_no_tls
        ssl_context = None
        server_type = "TCP"
        if tls:
            port = self.port_tls
            ssl_context = get_ssl_context(True)
            server_type = "TLS"
        # Initialise socket for IPv6 TCP packets
        # Address family (determines network layer protocol, here IPv6)
        # Socket type (stream, determines transport layer protocol TCP)
        sock = socket.socket(family=socket.AF_INET6, type=socket.SOCK_STREAM)

        # Allows address to be reused
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

        self.full_ipv6_address = await get_link_local_full_addr(port, self.iface)
        self.ipv6_address_host = self.full_ipv6_address[0]

        # Bind the socket to the IP address and port for receiving
        # TCP packets
        sock.bind(('', self.full_ipv6_address[1]))
```

Specifically, `sock.bind(self.full_ipv6_address)` was changed to `sock.bind(('', self.full_ipv6_address[1]))`.

Until know, was the only case that this issue was reported and  running the application in several other systems, didnt trigger this.
Thus, this is likely a specific issue with Designwerk system. 
The change to bind to all interfaces should be avoided for security reasons, so at least for now we wont adhere to this change.

Nevertheless, for the support of multiple connections as the interface is bounded to the PLC circuit that connects to a specific connector, we will need to bind the server to all interfaces

**Comment by martinbachmanndesignwerk** [comment]
The above issue is not existing anymore. The socket binding works as it is on master. @tropxy you can mark this issue as solved.
